loggers:
- log:
  kind: log
  env:
    logrus: Debug
    httplog: True
    gorm: False
providers:
- msad:
  kind: msad
  env:
    tenant_id: <MSAD_TENANT_ID>
    client_id: <MSAD_CLIENT_ID>
    client_secret: <MSAD_CLIENT_SECRET>
    authority: <MSAD_AUTHORITY>
    scopes: <MSAD_SCOPES>
    admin_group_name: ArgonAdmin
    use_group_name_pattern: False
- aws:
  kind: aws
  env:
    use_secret_store: True
    region: <AWS_REGION>
    access_key_id: <AWS_ACCESS_KEY_ID>
    secret_access_key: <AWS_SECRET_ACCESS_KEY>
    secret_name_prefix: c1secret_
servers:
- http:
  kind: http
  env:
    port: 1234
    address: 0.0.0.0
sqloptions:
- sql:
  kind: sql
  env:
    Max_Idle_Conns: 10
    Max_Open_Conns: 100
    Max_Lifetime: 1
backends:
- postgres:
  kind: postgres
  env:
    user: test
    pass: test
    dbname: argonadmindb
    host: localhost
    port: 5432
