loggers:
- log:
  kind: log
  env:
    logrus: Info
    httplog: True
    gorm: False
providers:
- msad:
  kind: msad
  env:
    tenant_id: hide
    client_id: hide
    client_secret: hide
    admin_group_name: hide
servers:
- http:
  kind: http
  env:
    port: 1234
    address: 0.0.0.0
sqloptions:
- sql:
  kind: sql
  env:
    Max_Idle_Conns: 10
    Max_Open_Conns: 100
    Max_Lifetime: 1
backends:
- postgres:
  kind: postgres
  env:
    user: test
    pass: test
    dbname: argonadmindb
    host: localhost
    port: 5432
