package config

const (
	DEFAULT_CONFIG_FILE_NAME   = "config.yaml"
	DEFAULT_IP_ADDRESS         = "127.0.0.1"
	DEFAULT_PORT               = "1234"
	DEFAULT_TENANT_ID          = ""
	DEFAULT_CLIENT_ID          = ""
	DEFAULT_CLIENT_SECRET	   = ""
	DEFAULT_SQL_MAX_IDLE_CONNS = 10
	DEFAULT_SQL_MAX_OPEN_CONNS = 100
	DEFAULT_SQL_MAX_LIFETIME   = 1
	DEFAULT_ADMIN_GROUP_NAME   = "DefaultAdmin"
)
